/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function (knex) {
  await knex("table_name").del();
  await knex("table_name").insert([
    {
      id: 1,
      title: "Shaun of the Dead",
      image: "/images/ShaunOfTheDead.jpg",
      director_id: 1,
      genre_id: 2,
      keyword_id: 1,
      trailer: "https://www.youtube.com/watch?v=LIfcaZ4pC-4",
      synopsis: "",
    },
    {
      id: 2,
      title: "Superbad",
      image: "/images/Superbad.jpg",
      director_id: 2,
      genre_id: 2,
      keyword_id: 5,
      trailer: "https://www.youtube.com/watch?v=4eaZ_48ZYog",
      synopsis: "",
    },
    {
      id: 3,
      title: "Mr Bean's Holiday",
      image: "/images/MrBeansHoliday.jpg",
      director_id: 3,
      genre_id: 3,
      keyword_id: 7,
      trailer: "https://www.youtube.com/watch?v=hSxLUd8aly4",
      synopsis: "",
    },
    {
      id: 4,
      title: "Reservoir Dogs",
      image: "/images/ReservoirDogs.jpg",
      director_id: 4,
      genre_id: 10,
      keyword_id: 8,
      trailer: "https://www.youtube.com/watch?v=vayksn4Y93A&t=43s",
      synopsis: "",
    },
    {
      id: 5,
      title: "Kill Bill: Vol 1",
      image: "/images/KillBillVol1.jpg",
      director_id: 4,
      genre_id: 6,
      keyword_id: 11,
      trailer: "https://www.youtube.com/watch?v=7kSuas6mRpk",
      synopsis: "",
    },
    {
      id: 6,
      title: "Kill Bill: Vol 2",
      image: "/images/KillBillVol2.jpg",
      director_id: 4,
      genre_id: 6,
      keyword_id: 11,
      trailer: "https://www.youtube.com/watch?v=WTt8cCIvGYI",
      synopsis: "",
    },
    {
      id: 7,
      title: "Lord of the Rings: The Fellowship of the Ring",
      image: "/images/lotrFellowshipOfTheRing.jpg",
      director_id: 5,
      genre_id: 8,
      keyword_id: 13,
      trailer: "https://www.youtube.com/watch?v=aStYWD25fAQ",
      synopsis: "",
    },
    {
      id: 8,
      title: "Lord of the Rings: The Two Towers",
      image: "/images/lotrTheTwoTowers.jpeg",
      director_id: 5,
      genre_id: 8,
      keyword_id: 13,
      trailer: "https://www.youtube.com/watch?v=Y4neBR0h39c",
      synopsis: "",
    },
    {
      id: 9,
      title: "Lord of the Rings: The Return of the King",
      image: "/images/lotrReturnOfTheKing.jpg",
      director_id: 5,
      genre_id: 8,
      keyword_id: 13,
      trailer: "https://www.youtube.com/watch?v=r5X-hFf6Bwo",
      synopsis: "",
    },
    {
      id: 10,
      title: "No Country for Old Men",
      image: "/images/NoCountryForOldMen.jpeg",
      director_id: 6,
      genre_id: 10,
      keyword_id: 15,
      trailer: "https://www.youtube.com/watch?v=38A__WT3-o0",
      synopsis: "",
    },
    {
      id: 11,
      title: "Hot Fuzz",
      image: "/images/HotFuzz.jpg",
      director_id: 1,
      genre_id: 2,
      keyword_id: 3,
      trailer: "https://www.youtube.com/watch?v=ayTnvVpj9t4",
      synopsis: "",
    },
    {
      id: 12,
      title: "Parasite",
      image: "/images/Parasite.jpg",
      director_id: 7,
      genre_id: 4,
      keyword_id: 17,
      trailer: "https://www.youtube.com/watch?v=5xH0HfJHsaY",
      synopsis: "",
    },
    {
      id: 13,
      title: "Midsommar",
      image: "/images/Midsommar.jpg",
      director_id: 8,
      genre_id: 1,
      keyword_id: 18,
      trailer: "https://www.youtube.com/watch?v=1Vnghdsjmd0",
      synopsis: "",
    },
    {
      id: 14,
      title: "The Grand Budapest Hotel",
      image: "/images/TheGrandBudapestHotel.jpg",
      director_id: 9,
      genre_id: 2,
      keyword_id: 19,
      trailer: "https://www.youtube.com/watch?v=1Fg5iWmQjwk&t=41s",
      synopsis: "",
    },
    {
      id: 15,
      title: "The French Dispatch",
      image: "/images/TheFrenchDispatch.jpg",
      director_id: 9,
      genre_id: 2,
      keyword_id: 19,
      trailer: "https://www.youtube.com/watch?v=TcPk2p0Zaw4",
      synopsis: "",
    },
    {
      id: 16,
      title: "Isle of Dogs",
      image: "/images/IsleOfDogs.jpg",
      director_id: 9,
      genre_id: 2,
      keyword_id: 23,
      trailer: "https://www.youtube.com/watch?v=dt__kig8PVU&t=90s",
      synopsis: "",
    },
    {
      id: 17,
      title: "The Darjeeling Limited",
      image: "/images/TheDarjeelingLimited.jpeg",
      director_id: 9,
      genre_id: 2,
      keyword_id: 22,
      trailer: "https://www.youtube.com/watch?v=aO1bYukdvLI",
      synopsis: "",
    },
    {
      id: 18,
      title: "Marcel the Shell with Shoes on",
      image: "/images/MarcelTheShellWithShoesOn.jpg",
      director_id: 10,
      genre_id: 11,
      keyword_id: 20,
      trailer: "https://www.youtube.com/watch?v=k98Afd7Nf3Y",
      synopsis: "",
    },
    {
      id: 19,
      title: "Fear and Loathing in Las Vegas",
      image: "/images/FearAndLoathingInLasVegas.jpg",
      director_id: 11,
      genre_id: 4,
      keyword_id: 4,
      trailer: "https://www.youtube.com/watch?v=CiTllYeJc48&t=17s",
      synopsis: "",
    },
    {
      id: 20,
      title: "The Death of Stalin",
      image: "/images/TheDeathOfStalin.png",
      director_id: 12,
      genre_id: 2,
      keyword_id: 34,
      trailer: "https://www.youtube.com/watch?v=E9eAshaPvYw",
      synopsis: "",
    },
    {
      id: 21,
      title: "Boiling Point",
      image: "/images/BoilingPoint.jpg",
      director_id: 13,
      genre_id: 4,
      keyword_id: 24,
      trailer: "https://www.youtube.com/watch?v=UBUfCL_tvro",
      synopsis: "",
    },
    {
      id: 22,
      title: "Chef",
      image: "/images/Chef.jpg",
      director_id: 14,
      genre_id: 3,
      keyword_id: 24,
      trailer: "https://www.youtube.com/watch?v=FF_rYNupPwg",
      synopsis: "",
    },
    {
      id: 23,
      title: "Spiderman: Into the Spiderverse",
      image: "/images/SpidermanIntoTheSpiderverse.jpg",
      director_id: 15,
      genre_id: 11,
      keyword_id: 25,
      trailer: "https://www.youtube.com/watch?v=g4Hbz2jLxvQ&t=4s",
      synopsis: "",
    },
    {
      id: 24,
      title: "Spiderman: Across the Spiderverse",
      image: "/images/SpidermanAcrossTheSpiderverse.jpg",
      director_id: 16,
      genre_id: 11,
      keyword_id: 25,
      trailer: "https://www.youtube.com/watch?v=shW9i6k8cB0",
      synopsis: "",
    },
    {
      id: 25,
      title: "Seven Psychopaths",
      image: "/images/SevenPsychopaths.jpg",
      director_id: 17,
      genre_id: 10,
      keyword_id: 4,
      trailer: "https://www.youtube.com/watch?v=jsHR77oQKEY",
      synopsis: "",
    },
    {
      id: 26,
      title: "In Bruges",
      image: "/images/InBruges.jpg",
      director_id: 17,
      genre_id: 10,
      keyword_id: 3,
      trailer: "https://www.youtube.com/watch?v=p-gG2qo_l_A",
      synopsis: "",
    },
    {
      id: 27,
      title: "Three Billboards Outside Ebbing, Missouri",
      image: "/images/ThreeBillboardsOutsideEbbingMissouri.jpg",
      director_id: 17,
      genre_id: 4,
      keyword_id: 27,
      trailer: "https://www.youtube.com/watch?v=Jit3YhGx5pU",
      synopsis: "",
    },
    {
      id: 28,
      title: "The Banshees of Inisherin",
      image: "/images/TheBansheesOfInishurin.jpg",
      director_id: 17,
      genre_id: 4,
      keyword_id: 28,
      trailer: "https://www.youtube.com/watch?v=uRu3zLOJN2c",
      synopsis: "",
    },
    {
      id: 29,
      title: "Moneyball",
      image: "/images/Moneyball.jpeg",
      director_id: 18,
      genre_id: 4,
      keyword_id: 29,
      trailer: "https://www.youtube.com/watch?v=-4QPVo0UIzc",
      synopsis: "",
    },
    {
      id: 30,
      title: "The Last Duel",
      image: "/images/TheLastDuel.jpg",
      director_id: 19,
      genre_id: 4,
      keyword_id: 30,
      trailer: "https://www.youtube.com/watch?v=mgygUwPJvYk",
      synopsis: "",
    },
    {
      id: 31,
      title: "Bullet Train",
      image: "/images/BulletTrain.jpeg",
      director_id: 20,
      genre_id: 7,
      keyword_id: 17,
      trailer: "https://www.youtube.com/watch?v=0IOsk2Vlc4o",
      synopsis: "",
    },
    {
      id: 32,
      title: "Toy Story",
      image: "/images/ToyStory.jpg",
      director_id: 21,
      genre_id: 11,
      keyword_id: 32,
      trailer: "https://www.youtube.com/watch?v=v-PjgYDrg70",
      synopsis: "",
    },
    {
      id: 33,
      title: "Toy Story 2",
      image: "/images/ToyStory2.jpg",
      director_id: 21,
      genre_id: 11,
      keyword_id: 32,
      trailer: "https://www.youtube.com/watch?v=t0bxljESZ5U",
      synopsis: "",
    },
    {
      id: 34,
      title: "Toy Story 3",
      image: "/images/ToyStory3.jpg",
      director_id: 22,
      genre_id: 11,
      keyword_id: 32,
      trailer: "https://www.youtube.com/watch?v=ZZv1vki4ou4",
      synopsis: "",
    },
    {
      id: 35,
      title: "Kubo and the Two Strings",
      image: "/images/KuboAndTheTwoStrings.png",
      director_id: 23,
      genre_id: 11,
      keyword_id: 21,
      trailer: "https://www.youtube.com/watch?v=qZefKaANfe0",
      synopsis: "",
    },
    {
      id: 36,
      title: "Drive",
      image: "/images/Drive.jpg",
      director_id: 24,
      genre_id: 5,
      keyword_id: 9,
      trailer: "https://www.youtube.com/watch?v=KBiOF3y1W0Y",
      synopsis: "",
    },
    {
      id: 37,
      title: "Goodfellas",
      image: "/images/Goodfellas.jpg",
      director_id: 25,
      genre_id: 10,
      keyword_id: 30,
      trailer: "https://www.youtube.com/watch?v=2ilzidi_J8Q",
      synopsis: "",
    },
    {
      id: 38,
      title: "The Wolf of Wall Street",
      image: "/images/TheWolfOfWallStreet.jpg",
      director_id: 25,
      genre_id: 4,
      keyword_id: 30,
      trailer: "https://www.youtube.com/watch?v=iszwuX1AK6A",
      synopsis: "",
    },
    {
      id: 39,
      title: "Shutter Island",
      image: "/images/ShutterIsland.jpg",
      director_id: 25,
      genre_id: 4,
      keyword_id: 15,
      trailer: "https://www.youtube.com/watch?v=v8yrZSkKxTA",
      synopsis: "",
    },
    {
      id: 40,
      title: "Monsters, Inc.",
      image: "/images/MonstersInc.jpg",
      director_id: 26,
      genre_id: 11,
      keyword_id: 32,
      trailer: "https://www.youtube.com/watch?v=CGbgaHoapFM",
      synopsis: "",
    },
    {
      id: 41,
      title: "Monsters University",
      image: "/images/MonstersUniversity.jpg",
      director_id: 27,
      genre_id: 11,
      keyword_id: 32,
      trailer: "https://www.youtube.com/watch?v=QxrQ6BaijAY",
      synopsis: "",
    },
  ]);
};
